# Generated by Django 5.1 on 2024-10-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_home_rating_homeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
