# Generated by Django 5.1 on 2024-10-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_remove_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='amenities',
            field=models.ManyToManyField(related_name='homes', to='Website.amenity'),
        ),
    ]
