# Generated by Django 5.1 on 2024-10-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_amenity_home_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='subheading',
            field=models.TextField(default='this is subheaeding'),
            preserve_default=False,
        ),
    ]
