# Generated by Django 5.1 on 2024-11-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=models.ImageField(upload_to='Website/static/image_uploads'),
        ),
    ]
