# Generated by Django 5.1 on 2024-11-16 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_alter_homeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='available_from',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='available_to',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
