# Generated by Django 5.1 on 2024-11-17 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_home_available_from_home_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='available_to',
            field=models.DateField(default=datetime.date(2099, 12, 31)),
        ),
    ]
