# Generated by Django 5.1 on 2024-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Enter the Bootstrap or FontAwesome icon class.', max_length=100),
        ),
    ]
